//
//  DataServices.swift
//  pwcs
//
//  Created by Zhilei Zheng on 1/20/18.
//  Copyright © 2018 Zhilei Zheng. All rights reserved.
//

import Foundation
import TimelineTableViewCell

class DataServices {
    
    static let shared = DataServices()
    
    private var panels = [PanelType : Panel]()
    private var panelSpeakers = [PanelType : [Speaker]]()
    private var rawPanels = [Panel]()
    private var rawSpeakers = [Speaker]()
    private var rawEvents = [Event]()
    private var schedules = [Int: [(TimelinePoint, UIColor, String, String, String?, String?, String?)]]()
    
    init() {
        readInPanels()
        readInSpeakers()
        readInSchedule()
        readInEvents()
    }
    
    func getSpeakers(for panelType : PanelType) -> [Speaker] {
        guard let speakers = panelSpeakers[panelType] else {
            return []
        }
        return speakers
    }
    
    func getPanel(for panelType : PanelType) -> Panel {
        guard let panel = panels[panelType] else {
            return Panel(name: "other", location: LocationType.special, time: "TBA", background: #imageLiteral(resourceName: "event-bg"), desc: "TBA")
        }
        return panel
    }
    
    func getPanels() -> [Panel] {
//        var results = [Panel]()
//        for (_ , panel) in panels {
//            results.append(panel)
//        }
//        return results
        return rawPanels
    }
    
    func getEvents() -> [Event] {
        return rawEvents
    }
    
    func getSchedule(for day : Int) -> [(TimelinePoint, UIColor, String, String, String?, String?, String?)]{
        guard let schedule = schedules[day] else {
            return [(TimelinePoint(), UIColor.black, "Other", "TBA", nil, nil, nil)]
        }
        return schedule
    }
    
    private func readInSpeakers() {
        readInRawSpeakers()
        for speaker in rawSpeakers {
            if panelSpeakers[speaker.panelType] == nil {
                panelSpeakers[speaker.panelType] = [Speaker]()
            }
            panelSpeakers[speaker.panelType]?.append(speaker)
        }
    }
    
    private func readInRawSpeakers() {
        rawSpeakers.append(Speaker(name: "Ying Fu", title: "Former Chinese Foreign Minster", desc: "Fu Ying became the Chairperson of the Foreign Affairs Committee of the National People’s Congress of China in March 2013, having joined China’s Foreign Service in the late 1970s. In 1992 in Cambodia, she became China’s first civilian UN peacekeeper and hence the start of her decade-long engagement with Asian affairs.  From 1993 to 2004, she served successively as the Director, Counselor of the Foreign Ministry’s Asian Department, Minister Counselor of the Chinese Embassy in Indonesia (1997), China’s Ambassador to the Philippines (1998), and head of the Foreign Ministry’s Asian Department (2000). She was appointed the Chinese Ambassador to Australia in 2004 and later Ambassador to the United Kingdom in 2007. From 2009 to 2013, she served as the Vice Minister of Foreign Affairs. She is now the Chair of Academic Committee of the newly established China’s Institute of International Strategy (CIIS) of Chinese Academy of Social Sciences (CASS), and specially invited Vice Chairman of China Center for International Economic Exchanges (CCIEE).", img: #imageLiteral(resourceName: "speaker-fu-ying"), panelType: .openingCeremony))
        rawSpeakers.append(Speaker(name: "Baoguo Zhu", title: " Founder and Chairman of Joincare and Livzon Pharmaceutical Group", desc: "Mr. Zhu dedicates a third of his time to philanthropy over the past decade. He serves as the core initiator and participant of The Paradise International Foundation (TaoHuaYuan); Secretary general and trustee of The Nature Conservancy’s China Global Conservation Fund Board Committee. Besides Pharmaceutical business, Mr. Zhu is also known as the joint founder with Tencent’s Webank.", img: #imageLiteral(resourceName: "speaker_baoguo_zhu"), panelType: .openingCeremony))
        rawSpeakers.append(Speaker(name: "Guangchang Guo", title: "Chairman of Fosun International Limited Representitive of the 12th Chinese People's\nPolitical Consultataive Conference", desc: "郭广昌先生祖籍浙江省东阳市，1989 年毕业于复旦大学哲学系，于1999 年获复旦大学工商管理硕士学位。1992 年，郭广昌先生与四位同学共同创建复星，并一直担任董事长一职。2007 年，复星国际（00656.HK）在香港联交所成功上市。目前，复星已成为一家植根于中国，“具有全球产业整合与资产配置能力”的全球性跨国投资集团。在此基础之上，复星将以家庭客户的需求为中心，以科技引领，智造一个植根中国的全球幸福生态系统。近年来，复星一直坚持“中国动力嫁接全球资源”的发展逻辑，并聚焦于健康、快乐和富足等领域。在大健康领域，复星医药、国药控股均已处于国内医药行业龙头，复星还投资了像和睦家医疗、葡萄牙Luz Saúde医院连锁、达芬奇手术机器人、微医集团（原挂号网）、宝宝树等国内外优秀大健康企业；在快乐领域，复星在已有法国地中海俱乐部、三亚亚特兰蒂斯、加拿大太阳马戏团、美国好莱坞Studio 8 公司等基础上，仍在以客户需求为导向整合全球资源；在富足产业中，复星先后投资或创立了永安保险、复星保德信寿险、香港鼎睿再保险、复星联合健康保险、复星葡萄牙保险、德国H&A私人银行、美国AmeriTrust、葡萄牙BCP银行、浙江网商银行、香港复星恒利证券等，初步形成了一张全球服务的金融网络。除此之外，复星在全球地产行业积极推行“蜂巢城市”模式，包括上海外滩金融中心、纽约Liberty 28、米兰布罗吉大厦等全球地标性建筑。郭广昌先生还热心社会公益事业，复星集团也立志成为一家负责任的全球企业。在过去二十余年中，郭广昌先生与复星公益基金会多次向扶贫助学、抗震救灾等社会事业捐赠款物；郭广昌先生也一直致力于推动中国文化与全球的交流，已经促成了中国企业家在纽约、伦敦、巴黎、柏林的多次交流；同时，复星还尤其注重用商业的手段来支持全球年轻人的创新、创业活动，如在中国及欧洲共同启动的Protechting项目，已吸引全球青年创业者积极参与其中。", img: #imageLiteral(resourceName: "speaker_guangchang_guo"), panelType: .openingCeremony))
        rawSpeakers.append(Speaker(name: "Dr. Philipp Rösler", title: "Chief Executive Officer of Hainan Cihang Charity Foundation", desc:"Dr. Rösler was appointed the inaugural Chief Executive Officer of Hainan Cihang Charity Foundation, the New York-based charitable organization established by HNA Group, in December 2017.  Under Dr. Rösler’s stewardship, and building on HNA Group’s philanthropic heritage and commitment to social responsibility, the Foundation aims to become one of the world’s leading charitable organizations beginning with its work on the Global Empowerment Initiative, which focuses on education, entrepreneurship and health as the wellsprings through which to make a lasting difference in poverty relief, refugee aid and many other important philanthropic causes.Prior to his current role, Dr. Rösler was Head of Regional and Government Engagement and a Member of the Managing Board at the World Economic Forum, where he was deeply involved in its work to transform the global humanitarian system by 2030, including through the creation of public-private partnerships.Dr. Rösler served as Vice Chancellor of Germany and Federal Minister of Economics and Technology, and Chairman of Germany’s Free Democratic Party from 2011 to 2013.  During his time as Federal Minister of Economics and Technology, Dr. Rösler led efforts to expand vocational training and foster entrepreneurship, particularly in the German start-up community via the German Silicon Valley Accelerator program.  From 2009 to 2011, he held the role of Germany’s Federal Minister of Health.Dr. Rösler started his political career as Secretary of the FDP in the state of Lower Saxony and was elected as Chairman of the Lower Saxon FDP in 2006.  He was later appointed State Minister for Economic Affairs, Labour and Transport, and Deputy Prime Minister in the cabinet of Christian Wulff of Lower Saxony.Dr. Rösler trained as a combat medic in the German Bundeswehr (the Federal Defence Force), where he achieved the rank of Stabsarzt, equivalent to an army captain.  He received a Degree in Medicine and a Doctorate Degree in Cardiovascular Surgery from the Hanover Medical School, and Honorary Doctorates in Economy from the University of Hanoi and in International Relations from the University of Cambodia.Born in Vietnam and adopted as an infant by German parents, Dr. Rösler was Germany’s first cabinet minister of Asian heritage.", img: #imageLiteral(resourceName: "speaker_philip_rosler"), panelType: .openingCeremony))
        rawSpeakers.append(Speaker(name: "Mang Su", title: "CEO of the Trends Media Group publishing house, Editor-in-chief of Harper's Bazaar China", desc: "苏芒，时尚集团总裁，中国第一代时尚人，在杂志、广告、编辑、运营等方面拥有最全面的时尚媒体经验，以开创性和发展性著称，是中国最具传奇色彩的媒体人。1994年加入时尚，创办及管理运营十余本杂志，包括《时尚伊人》、《时尚先生》、《时尚家居》、《时尚健康》、《时尚芭莎》等，其中《时尚芭莎》以独创性的模式及迅猛的发展速度，开创了7本芭莎品牌系列杂志的先河，成为全球范围内的奇迹，旗下品牌《芭莎艺术》不仅成为全世界发行量最大的艺术杂志，并因此带动了八个国家《芭莎艺术》的诞生。在如今的新媒体时代，带领集团在数字、视频、活动等领域多方发展的同时，亦联手行业外众多顶级企业进行跨界设计合作，开创了新的传媒运营模式。她不仅在杂志行业不断创新、锐意进取，更是一位赋有社会责任感的女性。她于2003年创办芭莎明星慈善夜，开创中国时尚慈善的先河，结合以时尚、明星、企业、品牌为一体的新模式，11年来共募款过两亿，成为中国规模最大、影响力最大的慈善活动品牌，帮助无数贫困家庭获得新生，两次荣获国家最高慈善奖项——中华慈善奖，并于2013荣获CCTV年度慈善人物。她毕业于中国音乐学院，曾获长江商学院EMBA学位，在服务于时尚集团20年间，苏芒善于带领团队，以时尚的方式推动慈善、公益、娱乐、艺术等方面并做出卓越的贡献，是中国最资深的时尚领军人物。", img: #imageLiteral(resourceName: "speaker_mang_su"), panelType: .openingCeremony))
        
        rawSpeakers.append(Speaker(name: "Ming Yang", title: "泰洋川禾创始人, CEO", desc: "杨铭，2009年毕业于中央戏剧学院导演系，中国顶尖经纪公司泰洋川禾创始人、CEO，后与papi酱（姜逸磊）共同创立知名短视频机构papitube。杨铭在2014年年底成立泰洋川禾，旗下合作艺人有Angelababy、周冬雨、陈赫。随后，相继与 王子文、谢娜、张杰、张钧甯等数十名艺人以及新生代歌手、导演、编剧等签署全约合作，帮助艺术家与创作者们找到在行业中的立足点。在三年间泰洋川禾在行业内发展迅速，已成为中国新一代经纪公司巨头。于2015年上半年，杨铭发现自媒体视频这一机遇，策划与姜逸磊合作拍摄短视频，使其粉丝总量暴增到近2500万。在2016年初，杨铭筹划了革命性的广告拍卖，获得2200万元广告投资，并将2200万元全额广告费捐赠给母校中央戏剧学院，用于新生代创作者培养。Papitube品牌机构也在Papi酱影响力下进行孵化，成为中文互联网最具影响力的短视频内容品牌之一。", img: #imageLiteral(resourceName: "speaker_ming_yang"), panelType: .fashion))
        rawSpeakers.append(Speaker(name: "Wen Zhou", title: "CEO of 3.1 Phillip Lim", desc: "As the CEO of 3.1 Phillip Lim, Wen Zhou is one of the most influential business women in the fashion industry. With her entrepreneurship and courageous vision, the Phillip Lim business had exceeded an annual revenue of $42 million in four years. At this moment, the brand is worth over $100 million. Considering Zhou’s incredible business mindset and Phillip Lim’s sartorial talents, the success of the brand is hardly a surprise. In 2015, the fashion duo won the Ernst & Young Entrepreneur of the Year Awards of New York while growing flagship stores in New York, Los Angeles, Miami, Honolulu, London, Tokyo, Beijing, Shanghai, Singapore , Hong Kong , Bangkok and Taiwan. As The Business of Fashion, the most professional fashion index, describes, “3.1 Phillip Lim has established itself as a respected business model and is seen as a pioneering force in the industry.” Born in Ningbo, China, Zhou embodies the perfect union of the east and the west. From owning her own fabric factory at the age of 21 to the founder of a fashion empire, Zhou has inspired millions of self-made woman and is on her way to greater accomplishments.", img: #imageLiteral(resourceName: "speaker_wen_zhou"), panelType: .fashion))
        
        rawSpeakers.append(Speaker(name: "Yue Yuan", title: "零点有数集团董事长、飞马旅联合创始人", desc: "Dr. Victor Yuan is chairman of Dataway Horizon, which is founded in 1992, providing data intelligence service for decision-making from data-recruiting to data-mining. He founded PEGASUS in 2011, committing to incubating and accelerating the entrepreneurial & innovative companies. And he is also president of YES: Horizon Center of Youth Entrepreneurship for Society, cultivating talented youth in the field of public welfare and pushing forward the development and social engagement of Chinese youth. ", img: #imageLiteral(resourceName: "speaker_yue_yuan"), panelType: .realEstate))
        rawSpeakers.append(Speaker(name: "Gehong Wang", title: "新派公寓创始人，赛富不动产基金合伙人", desc: "王戈宏，新派公寓创始人，赛富不动产基金合伙人。中国长租公寓创新领军人物，中国住房租赁资产证券化创新开拓者。2017年在深圳证券交易所率先成功挂牌中国第一支权益型住宅租赁类REITs，也是中国首支长租公寓类REITs，成为中国第一个比肩美国REITs模式金融创新的破冰标杆。新派公寓吸引来自欧美归国创业人才入住，海归达70%，成为欧美同学会命名的“海归创业驿站”。王先生是欧美同学会创业学院导师，中共北京朝阳区“凤凰计划”海外高层次人才，中共统战部海外归国优秀人才培训学员，美国丹佛大学研究学者、康奈尔大学国际人力资源证书，上海交通大学MBA、中国社会科学院金融博士专业。中国华人华侨创新创业联盟理事。", img: #imageLiteral(resourceName: "speaker_gehong_wang"), panelType: .realEstate))
        rawSpeakers.append(Speaker(name: "Xi Wang", title: "仁恒置地集团执行副总裁", desc: "建筑师、管理科学与工程硕士、战略管理学博士生。清华大学再教育学院房地产专业课程客座讲师,中房协房地产核心竞争力课题研究组组长，易居沃顿课题组导师。现任新加坡上市公司仁恒置地集团执行副总裁。曾任上海实业发展股份有限公司策划总监， 招商蛇口副总经理、华东区域总部总经理。房地产从业20余年。在国内房地产界率先提出项目前期策划理念和项目系统运营理论，擅长土地前期、策划设计、营销推广、项目管理及企业管理等工作，曾系统主责招商地产标准化产品体系、绿色建筑体系的研发和实施工作，并善于利用资本杠杆获取优质资源，在房地产投资和融资方面经验丰富。合计完成近30个城市、50多个项目的投融资和不同阶段的开发管理工作。", img: #imageLiteral(resourceName: "speaker_xi_wang"), panelType: .realEstate))
        
        rawSpeakers.append(Speaker(name: "Tiankai Cui", title: "第十任中华人民共和国驻美利坚合众国特命全权大使", desc: "1986年在美国霍普金斯大学国际公共政策获取硕士。曾先后担任过联合国总部中文秘书处译员、外交部国际司副处长、处长、参赞，外交部新闻司副司长、外交部发言人，常驻联合国代表团公使兼参赞，外交部政策研究室常务副主任、主任，外交部亚洲司司长，外交部部长助理，2007年至2009年担任中华人民共和国驻日本国特命全权大使，2009年担任外交部副部长。", img: #imageLiteral(resourceName: "speaker_tiankai_cui"),panelType: .internationalRelations))
        rawSpeakers.append(Speaker(name: "Kevin Rudd", title: "Former Australian Premier", desc: "陆克文先生于2007年至2010年出任澳大利亚第26届总理，于2010至2012年获任外交部长，并于2013年重返总理一职。陆克文先生是亚洲协会政策研究院（纽约及华盛顿）的创始主席。亚洲协会政策研究所（ASPI）致力于政策研究及二轨外交，帮助政府和企业应对亚洲内部及亚洲、美国和西方国家之间的政策与外交挑战。陆克文同时任哈佛大学肯尼迪政府学院高级研究员、美国国际战略研究中心（华盛顿）杰出政治家、英国皇家战略研究所（伦敦）荣誉成员、保尔森基金会（芝加哥）荣誉成员、世界和平机构国际多边机构改革委员会主席，以及全面禁止核试验条约组织筹备委员会知名人士小组成员。陆克文先生研习中文及汉学30余年，现为清华大学苏世民学院的国际顾问，北京大学名誉教授，也在牛津大学研究习近平治下的中国与世界。", img: #imageLiteral(resourceName: "speaker-kevin-rudd"),panelType: .internationalRelations))
        rawSpeakers.append(Speaker(name: "Avery Goldstein", title: "David M. Knott Professor of Global Politics and International Relations", desc: "Avery Goldstein is the David M. Knott Professor of Global Politics and International Relations in the Political Science Department, Director of the Center for the Study of Contemporary China, and Associate Director of the Christopher H. Browne Center for International Politics at the University of Pennsylvania. His research focuses on international relations, security studies, and Chinese politics. He is the author of Rising to the Challenge: China’s Grand Strategy and International Security (Stanford University Press, 2005), Deterrence and Security in the 21st Century: China, Britain, France and the Enduring Legacy of the Nuclear Revolution (Stanford University Press, 2000), and From Bandwagon to Balance of Power Politics: Structural Constraints and Politics in China, 1949-1978 (Stanford University Press, 1991). Among his other publications are articles in the journals International Security, International Organization, Journal of Strategic Studies, Security Studies, China Quarterly, Asian Survey, Comparative Politics, Orbis, and Polity as well as chapters in a variety of edited volumes. Goldstein is also a Senior Fellow at the Foreign Policy Research Institute in Philadelphia.", img: #imageLiteral(resourceName: "speaker_avery_goldstein"),panelType: .internationalRelations))
        
        rawSpeakers.append(Speaker(name: "Shuling Ying", title: "Founder and CEO of Hero Entertainment Group", desc: "英雄互娱（430127）集团创始人兼首席执行官，文化部电竞分会常务副会长，香港电子竞技联盟主席，国内手游发行业先导者，移动电竞领航人，14年、15年、16年中国杯帆船赛总冠军Hero船队船长。2015年6月16日，应书岭创办中国“移动电竞第一股”英雄互娱并成功在中国上市，华谊兄弟、红杉资本、分众传媒、真格基金、华兴资本、万众天地联合注资英雄互娱。英雄互娱以泛娱乐为战略目标，推广“移动电竞”，发展互联网体育，致力于为海内外用户提供优质的移动游戏内容，同时，英雄互娱也是中国在港澳台、东南亚地区最大的文化类出口企业。", img: #imageLiteral(resourceName: "speaker_shuling_ying"), panelType: .technology))
        rawSpeakers.append(Speaker(name: "Weixing Chen", title: "泛城控股有限公司董事长，“快的打车”创始人", desc: "曾获2015年第19届“中国青年五四奖章”、《福布斯》中国3030创业者等荣誉。先后创办了浙江泛城资产管理有限公司、杭州泛城科技有限公司、杭州快驰科技有限公司、杭州微易科技有限公司、通用计算集团、Fingo group等多家公司。泛城控股一直秉持着“服务技术创新  共建未来生态”的理念，专注于更为先进的生产力和更为公平的生产关系方面的最新技术的投资和研究，包括区块链、互联网金融、大数据、AI、IOT等领域，重点发现、整合并投资“超级独角兽”项目。公司已投资车和家、新潮传媒、51信用卡、氪空间、老虎证券、UT斯达康、OTMS、亿方云、爱上租、九州量子、现金白卡、51卡宝、华卓科技、咪哒、玩啊信息等80余家海内外优秀创业公司；同时，公司在区块链领域的投资与布局已在全国具有一定影响力，计划在未来两年内完成挖矿算力占全网算力的10%，拥有自己的交易所、加密货币钱包以及媒体社群，完成全产业链的生态建设，已投交易量全球排名第一的交易所币安Binance、交易量全球排名第五的交易所火币Huobi，虚拟币全球排名前20名的量子链QUTM、唯链VeChain、波场币TRON，以及ZB、EXX等近百个区块链相关项目。", img: #imageLiteral(resourceName: "speaker_weixing_chen"), panelType: .technology))
        rawSpeakers.append(Speaker(name: "Kebin Dai", title: "猎聘创始人兼CEO", desc: "2003年毕业于中山大学,2003-2008年担任P&G宝洁公司市场部大中华区品牌经理，管理过碧浪、护舒宝、佳洁士、欧乐B等品牌。2011年，由戴科彬创建的猎聘网正式上线，搭建了企业、猎头、经理人三方互动平台，全面提升了招聘与求职效率。戴科彬带领的猎聘团队始终以“帮助职场人更成功”为使命，实现每个人的价值。戴科彬先生2014年、2015年连续两年当选《财富》（中文版）“中国40位40岁以下的商界精英”。", img: #imageLiteral(resourceName: "speaker_kebin_dai"), panelType: .technology))
        rawSpeakers.append(Speaker(name: "Jeff Garzik", title: "Cofounder and CEO of Bloq", desc: "A futurist, entrepreneur and software engineer, Jeff Garzik is cofounder and CEO of Bloq, a blockchain enterprise software company. Jeff serves on the board of Coin Center, and the advisory boards of BitFury, BitPay, Chain.com, Netki and WayPaver Labs. He has delivered presentations on bitcoin and blockchain technology at TEDx, State of Digital Money, Scaling Bitcoin, as well as private briefings to corporations, governments, central banks, and hedge funds. Jeff was also recently appointed to the Linux Foundation Board of Directors, as well as the World Economic Forum Expert Network as an expert in Information Technology. Jeff has a long history of early technology adoption. After helping to inaugurate CNN.com on the Internet in the early 1990s, he worked for a succession of Internet startups and service providers. At the same time, he worked continuously on open source software engineering projects for over two decades. Involvement in one of the best known open source projects — the Linux kernel — led to an extended tenure at Linux market leader Red Hat during open source's most formative years. Jeff's work is found in every Android phone and data center running Linux today. In July 2010, Jeff stumbled across a post describing bitcoin. Immediately recognizing the potential of a concept previously thought impossible — decentralized digital money — he did what came naturally and developed bitcoin open source software. That gave rise to the start of micro-businesses with bitcoin at their foundation. Almost by accident, Jeff found himself at the heart of the global, revolutionary, technology phenomenon known as bitcoin.", img: #imageLiteral(resourceName: "speaker_jeff_garzik"), panelType: .technology))
        
        rawSpeakers.append(Speaker(name: "Albert Ng", title: "Chairman of EY China，Managing Partner of Greater China, Global Emerging Markets Committee Executive sponsor", desc: "Albert leads over 10,000 people in 23 offices at EY Greater China and has over 30 years' accounting experience in China. He is a pioneer in Chinese investment advisory services and provides business consultation to many multinational companies investing in the country. He also gives advice to Chinese companies on their domestic and overseas listings.Before joining EY, Albert was Managing Director of the China Investment Banking for Citigroup. And prior to this, he was a Managing Partner for Arthur Andersen Greater China.Today, Albert holds many positions in government and professional bodies. He has been an advisor to the International Business Leader's Advisory Council for the Mayor of Shanghai since 1995. He is a recipient of the Magnolia Gold Award, which was presented to him by the Shanghai city government in recognition of his services to the city. Albert was ranked among Global Accountancy Power 50 by International Accounting Bulletin in 2013 and 2014.", img: #imageLiteral(resourceName: "speaker_albert_ng"), panelType: .finance))
        rawSpeakers.append(Speaker(name: "Wei Yuan", title: "President of Tus-Holdings Co., Ltd.", desc: "Ms. Yuan Wei graduated from the school of Environmental Engineering and Institute of Economic Management in Tsinghua University in 1993 with a bachelor degree in engineering and economics; she graduated from 21st Century Development Research Institute of Tsinghua University in 1995 with a master degree in philosophy. From 1995 to 2000, she worked in the Intelligence Research Room of General Office of State Ministry of Science and Technology. Since 2000 she began working in venture capital industry with nearly 16 years of investment experience, and has focused on investment in the field of clean energy and energy conservation and environmental protection for a long time; she managed multiple Renminbi funds and dollar funds. She once successively served as a partner of Shanghai Lianchuang Investment Management Co., Ltd. And Redpoint Ventures, and founding management partner of South River Capital, etc. Ms. Yuan Wei served as a director or supervisor simultaneously in many listed companies. She joined TusHoldings in 2014 and serve as the President of Tus-Holdings Co., Ltd. now .", img: #imageLiteral(resourceName: "speaker_wei_yuan"), panelType: .finance))
        rawSpeakers.append(Speaker(name: "Dr. Guang Yang", title: "President of North America of HNA Group and the CEO of HNA Capital International", desc: "Dr. Guang Yang is the President of North America of HNA Group and the CEO of HNA Capital International. He is also the Founder and Chairman of Finergy Capital, a Beijing-based private equity fund. Dr. Yang was previously an Executive Vice President and Senior Portfolio Manager for Franklin Templeton Investments. He joined the Templeton Investment Counsel in 1995, where he had research responsibility for the European utilities and medical technology and supplies sectors, as well as regional coverage of Germany, China, and South East Asia. He managed global and international mutual funds as well as institutional separate accounts. He was also the Chairman of China for Franklin Templeton. Earlier in his career, he was a Research Scientist at Harvard Medical School and at Massachusetts General Hospital. Dr. Yang holds a B.S. from the University of Science and Technology of China, an MBA from Harvard Business School, and a Ph.D. in Neuroscience from Australian National University. Dr. Yang is also a Chartered Financial Analyst (CFA) charter holder.", img: #imageLiteral(resourceName: "speaker_guang_yang"), panelType: .finance))
        rawSpeakers.append(Speaker(name: "Yup S. Kim", title: "Senior Portfolio Manager of Private Equity and Special Opportunities at APFC", desc: "Mr. Yup S. Kim is a Senior Portfolio Manager of Private Equity and Special Opportunities at APFC, Alaska’s $66 billion sovereign wealth fund, where he helps lead their private investment activities globally. He sits on the private equity and special opportunities investment committees and serves as a board observer on several portfolio companies.Mr. Kim was recognized as a “Top 30 Sovereign Rising Stars” by Trusted Insight in 2016 and was honored as a “40 under 40” and a finalist for the “Next Generation Award” by the Chief Investment Officer magazine in 2017. His team was nominated for “Limited Partner of the Year - Americas” by Private Equity International Magazine in 2018. He regularly speaks at industry conferences, guest speaks at Harvard Business School for their private equity course and has written in publications for Privcap, Trusted Insight, Chief Investment Officer Magazine, Alaskan Chamber of Commerce, Juneau Empire and Anchorage Daily News.Mr. Kim received his B.A. in Economics from Yale University and speaks six languages.", img: #imageLiteral(resourceName: "speaker_yup_kim"), panelType: .finance))
        
        rawSpeakers.append(Speaker(name: "Zhenyao Wang", title: "教授，国际公益学院院长、北京师范大学中国公益研究院院长。", desc: "王振耀，教授，国际公益学院院长、北京师范大学中国公益研究院院长。哈佛大学肯尼迪政府学院公共管理硕士，北京大学政府管理学院法学博士。2015 年11月，王振耀教授受邀出任深圳国际公益学院院长。该学院由比尔·盖茨、瑞·达利欧、牛根生、何巧女、叶庆均五位中美慈善家联合倡议成立。学院致力于善知识体系的建设，努力提升中国公益教育专业化水平，促进公益慈善领域的国际交流与合作并推动全球慈善事业改革创新。2010年6月，北京师范大学聘任王振耀教授为中国公益研究院院长。该研究院致力于公益慈善、儿童福利和养老服务研究，在慈善立法、公益政策改革、儿童福利与养老服务体系建设的咨询方面完成了许多重要的项目，已经成为相当有影响力的中国公益智库。王振耀教授曾在国家民政部工作22年，为普及中国农村直接选举制度、建立城乡最低生活保障制度、创建国家自然灾害应急救助四级响应体系作出了重要贡献，在汶川地震救灾过程中受到国家表彰，并推动建立了孤儿津贴、老年人高龄津贴等多项国家基本社会福利制度。", img: #imageLiteral(resourceName: "speaker_zhenyao_wang"), panelType: .socialResponsibility))
        rawSpeakers.append(Speaker(name: "Jiangxue Pan", title: "\"真爱梦想\"基金会理事长", desc: "2016年10月，潘江雪作为长江商学院优秀学员及公益人，受邀在29期长江EMBA 启动仪式上进行分享，倡导企业家以商业思想迭代公益理念，参与社会问题的解决，承担企业家应担当的社会责任。在潘江雪的感召下，一些同学已走向公益3.0模式，在自己感兴趣的教育领域开启可持续的公益事业。2016年12月，真爱梦想举办了“看见未来”国际教育论坛，邀请了国内外专家学者共同探讨面向未来的教育。在全球化人类命运共同体下，真正的教育应该是帮助我们认识自己，从而教会我们如何更好地生存下去。潘江雪的方式是透过跨界学习来反思和看见教育的未来，这也是真爱梦想能够一直保持公益创变的原因。2017年初， 真爱梦想获“界面2016中国最透明慈善公益基金会”第一名，在接受采访时潘江雪说：公益组织的核心竞争力是公益服务和产品，透明只是公开的呈现方式，真爱梦想的工作理念是“公开透明，专业高效”。2017年是潘江雪创办真爱梦想十周年，在6月她回到了十年前四川阿坝州马尔康的第一间梦想中心，从当初一个人小小助学心愿，到今天变成了一个遍布全国2800多所学校的素养教育产品和服务网络，十年间越来越多的人加入推动中国素养教育实践的行动中，十年前，梦从马尔康开始，十年后，梦想升级，从心出发。", img: #imageLiteral(resourceName: "speaker_jiangxue_pan"), panelType: .socialResponsibility))
        rawSpeakers.append(Speaker(name: "Fei Deng", title: "《凤凰周刊》编委", desc: "2011年转身公益，他先后发起微博打拐、免费午餐、大病医保、暖流计划、儿童防侵、让候鸟飞、中国水安全计划、拯救古建、青螺公益、会飞的盒子、拾穗行动等公益项目和e农计划、青螺学堂等社会企业，致力增加乡村儿童权利，发展乡村经济和乡村人力资源培训，努力构建中国乡村问题系统解决方案。他使用众筹众包，开创了互联网微公益，掀起一场中国公益慈善界革命。在他实践下，“透明公益”、“人人公益”和＂柔软改变中国＂等理念深入人心，推动了政府、企业、社会三方合作，有效解社会问题。2014年，邓飞获达沃斯经济论坛全球青年领袖。", img: #imageLiteral(resourceName: "speaker_fei_deng"), panelType: .socialResponsibility))
        rawSpeakers.append(Speaker(name: "Xudong Zhu", title: "易居中国的联合创始人, 宝库中国执行董事, 太德励拓公关传媒集团董事长／总裁, 易居乐农董事长", desc: "朱旭东是易居中国的联合创始人，成立于2000年的易居（E～house）集团先后拥有6家上市公司，目前在全国近100个城市开展各类房地产线上线下服务业务，近4万名员工，2017代理销售金额突破5000亿，成为中国房地产服务行业的领军企业。目前，朱旭东先生全权负责易居集团旗下最新的文化产业服务板块的管理运营。易居文化产业服务板块拥有中国最大的房地产公关传播集团～TED太徳励拓集团（NEEQ：837383）和中国艺术领域的基础设施及平台建设投资服务商～宝库文化，专注于公关传媒，宝库一号及宝库艺术中心和博物馆的建设与运营，并专注展览交易，艺术品储存，艺术金融等艺术文化产业链的创新发展。2018年起，朱旭东兼任易居乐农的董事长，担负起整合城市社区资源和力量，为精准扶贫伟大工程服务的重担，并担任了中国扶贫社区联盟的主席，利用移动互联网，把田间村头和城市社区直接链接，通过社区家庭的日常消费，来带动贫困地区农产品的销售，帮助农民脱贫致富。社会创新特别专题。", img: #imageLiteral(resourceName: "speaker_xudong_zhu"), panelType: .socialResponsibility))
        
        rawSpeakers.append(Speaker(name: "Sai Wang", title: "益桥创始人，罗德学者", desc: "出生于山西，曾就读于多伦多大学、巴黎政治学院、耶路撒冷希伯来大学，攻读国际关系学，后以罗德学者身份在牛津大学获得公共政策硕士学位，并三次推迟哈佛大学法学博士的入学。近年来，王赛多次回到祖国，为中国社会发展尽一己之力，包括加入美丽中国教育项目，在云南保山担任项目主管；任职于北京大学燕京学堂，负责培养来自世界顶尖大学的中国与国际学生；曾参与东非社区发展项目与丰台农民工法律援助等项目。此外，他还担任清华大学苏世民学者导师以及北京大学法学院全球高端人才培养项目导师。王赛曾当选世界经济论坛杰出青年代表，并入选福布斯 30 Under 30。益桥中国是一家开创型的社会创新机构，寓意为“公益之桥”，致力于把优秀人才和跨界资源带入中国公益行业，创新性地解决社会问题，并激发社会大众对公益的理解与参与。“益桥伙伴计划”面向全球华人青年，旨在培养有益于中国发展的社会创新领袖，让海内外优秀华人毕业生和职业人士有机会进入中国顶尖的公益机构工作，同时给予其导师、培训、社群、经费等丰富的资源支持，使其快速提升自我，建立社会影响，并构筑起一个在各行业间相互支持、共同引领的社群。", img: #imageLiteral(resourceName: "speaker_sai_wang"), panelType: .special))
        rawSpeakers.append(Speaker(name: "Shiming Miao", title: "WABC 创始人", desc: "1980 年河北邯郸人，毕业于中央美术学院，是一位艺术家和策展人。2003 年至 2009 年间任艺术教师，其余时间进行艺术创作和艺术展览策划，同时关注艺术文化方面的活动。一次偶然的机会（2009 年首届北京 798 双年展）让苗世明走进了“特殊需要人群”的生活，他们的现实状况深深震撼了他。结合自己以往艺术培训和教学的经验，苗世明尝试以艺术的方式和他们交朋友，走进他们的心灵深处，那是一种无比奇妙的经历。在教学过程中苗世明发现他们很多人是具有艺术天赋的，而且艺术实践也的确在一定程度上改善了他们的心理状态和情绪。后来苗世明得知国外有类似的专门机构和组织，那中国为什么不可以有呢！苗世明觉得这是一项值得为之奋斗的事业，虽然困难重重，但意义非凡。随后他创办了公益项目“WABC 无障碍艺途”，并于 2010 年在上海市民政局的支持下登记注册“上海艺途无障碍工作室”。至此，“无障碍艺途”（WABC，全称为 World of Art Brut Culture，即“原生艺术的世界”）以 NGO 组织的形式在上海正式落地。2014 年，WABC 无障碍艺途上海艺术工作室入驻上海公益地标「公益新天地」园区。WABC 发展至今，已在上海、北京、杭州、成都、深圳、广州、西安、珠海、南京等 10 个城市，30 余个社区点为精智障碍特殊人士提供艺术疗愈课程。", img: #imageLiteral(resourceName: "speaker_shiming_miao"), panelType: .special))
    }
    
    private func readInPanels() {
        rawPanels.append(Panel(name: "Investment Panel", location: LocationType.irvineAuditorium, time: "12:30 PM - 2:30 PM | Saturday", background: #imageLiteral(resourceName: "panel-bg-shanghai"), desc: "Disruptions and opportunities: shaping new investment landscape in China\nFor the past decade, the world economy has endured a long period of slow recovery. Low real interest rates, declining productivity growth, and lack of attractive domestic investment opportunities are forcing global investors to seek higher returns in less familiar territories. During this process, emerging markets, specifically China, has stood out with its rapid developments in almost all areas of the economy.\nDuring the third-quarter 2017, China reported a 6.8 percent GDP growth, cooling from a 6.9 percent expansion in the previous quarter, but exceeding year-start consensus of 6.5 percent. Some speculators view it as a sign of China exhausting its growth potential. Indeed, with constant concern about the highly leveraged capital structure, China's growth prospect is under heavy scrutiny. Moreover, a new wave of protectionism initiated by the U.S. is clouding the global market with angst and uncertainty. How will the additional tariffs on imports imposed by the United States affect the global economy, especially with respect to China? How is the U.S. unfriendly standpoint on its trade deficit with China affecting international investors' decision making? On the brink of a potential trade war, how can China confront the challenge under protectionist measures?\nOne side of economists and financial analysts are taking a bearish view on China. After years of loose monetary policies and financial regulations, shadow banks and private lenders have entrenched themselves to be a huge part of the economy. Many fear that this has exposed the financial markets to future crises and volatility. Meanwhile, easy credit has also propped up real asset prices to overheated levels. Does China have the superior services, innovative technology, and consumer demand necessary to offer truly long term growth opportunities to investors and businesses? Nevertheless, as China shifts from an export-driven growth model towards a domestic consumption-driven growth model, there will be more room for global investors to participate. In addition, China, leading the globalization initiative with its \"One Belt, One Road\" policy, is creating a myriad of opportunities for other world economies. \nWith continuous regulatory changes, constant technological, industry, and policy disruptions, and rising valuations across major asset classes, how can global investors better navigate the volatile but evolving Chinese market and economy? How can investors prepare themselves to capitalize on the new wave of opportunities in China? How does the recent wave of protectionism initiated by the U.S. affect investor sentiment? What role should China play in the next generation of Globalization?"))
        rawPanels.append(Panel(name: "Real Estate Panel", location: .annenburgCenter, time: "12:30 PM - 2:30 PM | Saturday", background: #imageLiteral(resourceName: "panel-bg-1"), desc: "The New Direction of Chinese Real Estate Development\n近年来中国房地产投资增速持续下滑，库存不断攀升，销售增长出现疲态。政府出台一系列刺激政策，并将\"去库存\"列为中央经济工作会议上主要任务之一。在此背景下，一线城市房地产市场率先复苏，而二三线城市的市场表现则差强人意，城市间分化格局进一步加剧。面对当下的楼市特征，房地产行业应如何突破瓶颈，转换思维，优化盈利模式，实现房地产市场从结构到功能的根本转变，成为迫在眉睫的焦点话题。\n房地产经营业态正值转型之际，不同的转型模式正不断涌现：以特色小镇，养老地产，生态产业园为代表的多元服务板块正逐步兴起以满足购房者更高更准确的购房需求；如凯德、万达等领头的商业综合体开发商近些年成功打破原有的商业地产格局，将多方资源整合，逐渐形成各具特色的商业综合体开发模式；随着消费升级，旅游业的快速兴起，配合旅游需求开发的体验式旅游房产项目也正吸引众多房企的关注；而在政府对房屋租赁市场发展的大力推动下又催生了一批专注于长租公寓的房地产企业，越来越多的地产项目被作为公租房开发。\n在当下这个充满变革与机遇的时间节点，企业该如何实现从传统模式到新模式的平稳过渡？企业如何在众多转型方向中量体裁衣，避免盲目跟从？国家对这些新模式的兴起又持有怎样的态度与预期？本分论坛将探讨新兴房地产模式与传统房地产模式的碰撞与融合。"))
        rawPanels.append(Panel(name: "International Relations Panel", location: .annenburgCenter, time: "3:00 PM - 5:00 PM | Saturday", background: #imageLiteral(resourceName: "panel-bg-beijing"), desc: "Mutual Trust and Challenges: A Global Perspective of US-China Relations\nAs we are approaching a new decade, no relationship will be as important to the twenty-first century as the one between the United States, the largest developed country, and China, the largest developing country. As the world's two foremost economic superpowers, how could United States and China avoid the \"Thucydides Trap\"- recurrent conflicts between the existing and rising powers. Under the present wave of globalization, could Sino-US cooperation become the new status quo? Currently, some Americans support U.S. pursuing an integrative strategy with China as the latter continue to expand its global presence. Some others, with an alternative understanding of China and the dynamics of the world, believe that China's strategic interests are incompatible with those of United States. How to put today's China in perspective? Which areas in particular should China and US increase their cooperation to boost mutual trust and understanding?\nAt Mar-a-Lago, President Xi said to President Trump, \"There are a thousand reasons for us to make China-U.S. relations work, but not a single reason to break it\". The two presidents have made a lot of success in reaching agreements on building better connectivity in different areas and at various levels.  The White House has confirmed President Trump's visit to China in November, another affirming sign of strong fostering of Sino-US relations.\nIn today's world, how to make sense of the consensus between the two presidents and the significance of the Belt and Road initiative? From these significant summits and forums, many people, particular the students, want to know what are the takeaways for them? What will be the impact of Sino-US relationship on their lives? What can the 21st century students particularly contribute to help strengthen the two countries' relationship?"))
        rawPanels.append(Panel(name: "Fashion and Entertainment Panel", location: .irvineAuditorium, time: "3:00 PM - 5:00 PM | Saturday", background: #imageLiteral(resourceName: "panel-bg-la"), desc: "The New Age of Entertainment: Building the U.S-China Cultural Platform\n In our generation, Chinese entertainment is gradually entering the world stage. We strive to redefine \"made in China\" in this new era with creativity and a global vision. While the rapid development of technology, especially the internet, transforms our perception of the media, productions and designs are breaking the cultural boundaries between countries. In the past few years, the entertainment industries in China and the United State have benefited from close collaborations. Looking forward, our generation will spark more inspirations, discover new talents, and establish meaningful relationships by building a cultural platform between China and the world. As we seize opportunities and face challenges, we have the courage and the determination to build the new age of Chinese entertainment."))
        rawPanels.append(Panel(name: "Social Responsibility Panel", location: .annenburgCenter, time: "10:00 AM - 12:00 PM | Sunday", background: #imageLiteral(resourceName: "panel-bg-chicago"), desc: "Corporate Sustainability and Social Responsibility\n\"Our generation\" is not only one that excels in innovation and dares to challenge, but also a generation that assumes social responsibility while practicing sustainable development.\nToday, with the transformation of China's economic structure, many social problems have started to come about, and the implementation of the national 13th five-year plan and sustainable development goals faces many opportunities and challenges. With the efforts of all the explorers and practitioners, as well as the integration of business, media, science and technology, innovation and culture, China's philanthropic industry is developing in a positive way. For enterprises, the realization of social value is as important as that of the commercial value. The public welfare element can aid the construction of enterprise brand and culture, the promotion of social influence and the transformation of strategy. For public welfare institutions, the linkage of social resources is conducive to the improvement and solution of social problems. For government and media, focusing on social issues, promoting social development, and spreading the positive energy of society have always been needed.\nTherefore, our panel will invite outstanding entrepreneurs to discuss the status, problems, solutions and future prospects of sustainable development and social responsibility of Chinese enterprises."))
        rawPanels.append(Panel(name: "Blockchain Panel", location: .irvineAuditorium, time: "10:00AM - 12:00 PM | Sunday", background: #imageLiteral(resourceName: "panel-bg-seattle"), desc: "Challenges and Opportunities from Technological Innovation\nWhat comes to your mind when you hear \"blockchain\"? Many would say Bitcoin. Bitcoin is a decentralized, blockchain based currency that uses Private Key as a digital signature and allows P2P payment without the need of a 3rd party such as a bank or a securities firm. Bitcoin can reduce expensive transaction fees and increase trust in the financial sector. Blockchain's transparency, security, efficiency, and the lack of a middleman gives it the potential to be applied to numerous other industries such as supply chain management, internet of things, insurance, cloud storage, governments, hospitals, energy management, retail, and real estate. In today's digital age, blockchain has the potential to become the revolutionary technology behind the fifth industrial revolution."))
    }
    
    private func readInEvents() {
        rawEvents.append(Event(name: "INNO Talk", location: .annenburgCenter, time: "7:00 PM - 9:00 PM | Saturday", desc: "承接上一代开拓者的脚步，我们这一代也在探索那些振奋人心的创业理想。为了提供全球化的视野给新一代的创业者，沃顿峰会设立了InnoTalk（创业对话）这一活动。InnoTalk致力于为中美创新创业者，领域搭建信息互换的桥梁。活动流程将以峰会的六个板块作为背景，邀请社会责任，房地产，文娱，科技，国际关系，金融等领域的6名杰出北美创业代表来现场进行话题分析。6个不同领域的团队将依次演讲展示各自的创业成果与理念，并与5位特邀嘉宾和现场观众进行Q&A互动。", background: #imageLiteral(resourceName: "event-bg")))
        rawEvents.append(Event(name: "Recruiting Panel", location: .innAtPenn, time: "6:00 PM - 9:30 PM | Friday", desc: "想知道国内HR最看重海归身上的哪些特质吗？\n想了解留学生回国就业最佳的发展方向有哪些？\n想倾听人力资源专家对于海归优劣势、竞争力、就业趋势的看法吗？\n想让资深企业人解答你求职、创业中遇到的困惑吗？\n我们相约于宾大沃顿中美峰会与猎聘北美携手主办本届<职业发展论坛>，将带给观众带来最理性的职业分析和最宝贵的求职经验。届时为大家邀请到了5位最资深的企业人和人力资源专家，以\"北美留学生的职业发展\"、\"留学生竞争力\"、\"留学生回国就业趋势\"等留学生求职话题进行现场探讨。活动期间，峰会筹委会将带来十余家知名企业进行现场招聘，为求职者提供一个现场求职的机会。", background: #imageLiteral(resourceName: "event-bg")))
        rawEvents.append(Event(name: "Career Fair", location: .annenburgCenter, time: "5:00 PM - 7:30 PM | Saturday", desc: "沃顿中美峰会致力于构建中国与海外精英们的民间纽带，搭建海外菁英启发与就职的交流平台。本次招聘会旨在连结中美两国的优秀学子，帮助中美优质企业与海外优秀学子的对接，并为有意向在北美发展的中国企业和美国企业物色拥有海外经验的优秀人才。部分参与此次招聘会的企业名单如下：招商银行，建信信托，药明康德，英雄互娱,中国人寿，小米，TalkingData, 猎聘网, OPPO, UB TECH, 北美留学日报等。", background: #imageLiteral(resourceName: "event-bg")))
    }
    
    private func readInFAQ() {
        
    }
    
    private func readInSchedule() {
        schedules = [0:[
            (TimelinePoint(), UIColor.black, "Audience Registration", "2:00 PM - 6:00 PM\nHilton Inn At Penn\nAudience register arrival with staff. Summit brochure, and badge will be distributed.", "4 Hours", nil, "Sun"),
            (TimelinePoint(), UIColor.black, "Press Release", "4:00 PM - 6:00 PM\nSheraton in University City\nPresentation by representatives from the Summit Board and the Wharton school to media.", "2 Hours", nil, "Sun"),
            (TimelinePoint(), UIColor.black, "Career Fair and Panel Presentation", "6:00 PM - 8:00 PM\nHilton Inn At Penn\nPresentation by representatives from the Summit Board, Liepin and HR from participating companies.", "2 Hours", nil, "Sun"),
            (TimelinePoint(), UIColor.black, "Cocktail Social", "6:00 PM - 7:00 PM\nHuntsman Hall 8th Floor\nCocktail social co-hosted by Summit Board and the Wharton School.", "1 Hour", nil, "Sun"),
            (TimelinePoint(), UIColor.clear, "VIP Dinner", "7:00 PM - 9:00 PM\nHuntsman Hall 8th Floor\nBlack-tie dinner co-hosted by Summit Board and the Wharton School.", "2 Hours", "Apple", "Sun")
            ], 1:[
                (TimelinePoint(), UIColor.black, "Audience Registration - Regular", "8:00 AM = 10:00 AM\nLocation TBD\nAudience register arrival with staff. Summit brochure, and badge will be distributed.", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.black, "Audience Registration - Late", "10:00 AM - 1:00 PM\nLocation TBD\nAudience register arrival with staff. Summit brochure, and badge will be distributed.", "3 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "Opening Ceremony", "9:00 AM - 11:00 AM\nIrvine Auditorium\nWelcoming speech will be given by Summit President and Dean of the Wharton School, followed by five keynote speakers.\nSpeakers: Fu Ying, Guo Guangchang, Zhu Baoguo, Su Mang, Philip Rosler", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "Real Estate Panel", "12:30 PM - 2:30 PM\nAnnenberg Center\nSpeakers: Zhou Xin, Yuan Yue, Wang Xi, Wang Gehong", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "Investment Panel", "12:30 PM - 2:30 PM\nIrvine Auditorium\nSpeakers: Albert Ng, Yup Kim, Yang Guang", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "International Relations Panel", "3:00 PM - 5:00 PM\nAnnenberg Center\nSpeakers: Fu Ying，Kevin Rudd，Cui Tiankai", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "Fashion and Entertainment Panel", "3:00 PM - 5:00 PM\nIrvine Auditorium\nSpeakers: Zhou Wen, Yang Ming, Su Mang", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "Career Fair", "5:00 PM - 7:30 PM\nAnnenberg Center\nCareer Fair by participating companies, Audience can deliver resume and exchange contact.", "2 Hours 30 mins", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "INNO Talk", "7:00 PM - 9:00 PM\nAnnenberg Center\nConversation between startups, industry leaders and investors.", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.clear, "Special Event and Social Innovation", "7:00 PM - 9:00 PM\nThe Study\nYoung global leaders sharing stories of innovation.", "2 Hours", "Apple", "Sun")
            ], 2:[
                (TimelinePoint(), UIColor.black, "Corporate Sustainability and Social Responsibility Panel", "10:00 AM - 12:00 PM\nAnnenberg Center\nSpeakers: Zhu Xudong, Deng Fei, Wang Zhenyao, Pan Jiangxue", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.black, "Blockchain and Application in China’s Economy Panel", "10:00 AM - 12:00 PM\nIrvine Auditorium\nSpeakers: Ying Shuling, Chen Weixing, Dai Kebin, Jeff Garzik", "2 Hours", nil, "Sun"),
                (TimelinePoint(), UIColor.black, "Closing Ceremony", "12:30 PM - 3:15 PM\nIrvine Auditorium\nClosing remarks will be given by Summit Vice President and Vice Dean of the Wharton School, followed by four keynote speakers.\nSpeakers: Cui Tiankai, Pete Walker, Wang Zhenyao", "2 Hours 45 mins", "Apple", "Sun")
            ]]
    }
    
}
